[tool.poetry]
name = "-env"
version = "0.1.0"
description = ""
authors = ["vdanh <vdanhvt2000@gmail.com>"]
readme = "README.md"
packages = [{include = "env"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
